import "../styles/globals.css";
import Head from "next/head";
import Layout from "../components/Layout";
import { AppWrapper } from "../context/AppContext";
// style of react-toastofy
import 'react-toastify/dist/ReactToastify.css'; 


function MyApp({ Component, pageProps }) {
  return (

    <AppWrapper>
      <Layout>
        <title>گیراوب|آموزشگاه تخصصی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://s6.uupload.ir/files/logo_mmle.jpg" />
        <Component {...pageProps} />
      </Layout>
      </AppWrapper>
  );
}

export default MyApp;
