import '../styles/globals.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return <div>
      <Head>
        <title>گیراوب|آموزشگاه تخصصی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://s6.uupload.ir/files/logo_mmle.jpg" />
      </Head>
    <Component {...pageProps} />
  </div>
}

export default MyApp



{/* <Head>
<meta charset="UTF-8" />
<meta name="keywords" content="titla, meta, nextjs" />
<meta name="author" content="Syamlal CM" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</Head> */}