import Contact from "../components/Contact";
import Head from "next/head";

const contact = () => {
    return ( <>
      <Head>
        <title>ارتباط با ما |گیراوب</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://s6.uupload.ir/files/logo_mmle.jpg" />
      </Head>
<Contact/>
    </> );
}
 
export default contact