import Head from "next/head";
import { useEffect } from "react";
import Login from "../components/Login";
import { useAppContext } from "../context/AppContext";




const LoginPage = () => {
  const [appState, setAppState] = useAppContext();
 useEffect(()=>{
   setAppState("marg")
 },[])
  console.log(appState);
  return (
    <div>
      <Head>
        <title>صفحه ورود به سایت</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://s6.uupload.ir/files/logo_mmle.jpg" />
      </Head>
      <Login />
    </div>
  );
};

export default LoginPage;
