import Register from "../components/Register";
import Head from "next/head";

const RegisterPage = () => {
  return (
    <div>
      <Head>
        <title>صفحه ثبت نام</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://s6.uupload.ir/files/logo_mmle.jpg" />
      </Head>
      <Register />
    </div>
  );
};

export default RegisterPage;
